import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const md = fs.readFileSync(path.join(root, 'README.md'), 'utf8');
assert.match(md, /rvp-design\/gnfp_cminer/);
assert.match(md, /5%/);
assert.match(md, /\*\*miner\*\* fee|miner fee|dual-login miner/i);
assert.match(md, /1%/);
assert.match(md, /not a pool tax/i);
assert.match(md, /dual-login|second connection/);
assert.match(md, /gnfp19381c4b1d7a9cbae64120f24b16d248ae07c6ff1/);
assert.match(md, /stripped Linux ELF|closed ELF/);
assert.match(md, /GNFPHash-v1/);
assert.match(md, /TLS/);
assert.match(md, /Official/);
assert.match(md, /deprecated/i);
assert.match(md, /1\.1\.1/);
assert.doesNotMatch(md, /Pin \*\*1\.1\.0\*\*/);
assert.match(md, /gnfp-cminer-1\.1\.1-macos\.tar\.gz/);
assert.match(md, /gnfp-cminer-1\.1\.1-linux\.tar\.gz/);
assert.match(md, /gnfp-cminer-1\.1\.1-windows\.zip/);
assert.doesNotMatch(md, /gnfp-cminer-1\.1\.0-macos\.tar\.gz/);
assert.doesNotMatch(md, /gnfp-cminer-1\.1\.0-linux\.tar\.gz/);
assert.doesNotMatch(md, /gnfp-cminer-1\.1\.0-windows\.zip/);
assert.match(md, /no `--threads` 256 clamp/i);
assert.match(md, /github.com\/rgsneddon\/gnfp-cminer/);
assert.match(md, /--selftest/);
assert.match(md, /--user/);
assert.match(md, /--threads/);
assert.match(md, /de\.restoreprivacy\.online:1474/);
assert.doesNotMatch(md, /Repo is \*\*private\*\*/);
console.log('README credit/fee/hash notes ok');
